### PR TITLE
Sadie/update for secure cadence

### PR DESCRIPTION
**Pull request by sadief**
We need to update the `flow-pds` to use the following versions due to some [breaking changes](https://forum.onflow.org/t/breaking-changes-coming-with-secure-cadence-release/3052) incoming for Cadence. 

```
	github.com/onflow/cadence v0.21.3-0.20220422215834-5ba7ff3666fd
	github.com/onflow/flow-cli v0.33.2-0.20220425184358-8797257ba650
	github.com/onflow/flow-go-sdk v0.24.1-0.20220421152843-9ce4d554036e
```

The `flow-pds` has a dependency on this library which also needs to be updated. I bumped the versions but had to base off a different version from what is in the main branch as this is what the `flow-pds` is pointing towards:

`replace github.com/bjartek/go-with-the-flow/v2 => github.com/flow-hydraulics/go-with-the-flow/v2 v2.0.0-20210916131243-1b2f9db5a593`

Most of the code here is updated from some internal library changes that I hacked at to get working. The main Cadence upgrade changes are fixing a few functions from the SDK which have changed function signature (eg. `cadence.NewString()` which now produces an error).

I'm open to a better way of doing this - would appreciate any help as we are on a time crunch to have this working by next week. This _seems_ to work so far, at least when I run the tests through the `flow-pds` by pointing at my local branch, but further testing is required.

The testing suite is also erroring in several places, however this seems to be the case for the commit that I forked from with the main culprit the `TransactionFromFile()` signature changing. This is not related to the Cadence change - would appreciate any guidance on how to fix that.

### CODE REVIEW

**Comment by sadief** [comment]
Updated to latest version as realized it didn't need to point to the older version from pds- closing this in favour of https://github.com/flow-hydraulics/go-with-the-flow/pull/2

**Comment by sadief** [comment]
Reopening as this maintains the function signature from `TransactionFromFile` which the `flow-pds` utilizes heavily and it appears to break once the `code` parameter is removed. Any guidance on this would be much appreciated. Right now there's two PRs:
- One based off of `1b2f9db5a593` which is the compatible version with `flow-pds` #1 
- One based off of Main #2

The second requires fewer changes however is not compatible with `flow-pds`.

**Comment by sadief** [comment]
@bjartek @whalelephant @nanuuki @aphelionz maybe you have ideas/thoughts?

**Comment by bjartek** [comment]
Go-with-the-flow is deprecated in favor of https://github.com/bjartek/overflow.

It has a secure-cadence branch.

If your fork of gwtf has changes you need in overflow I am sure they can be added.

**Comment by sadief** [comment]
Thank you @bjartek - I've ported over the PDS to overflow. I wonder if it would be possible to mark the go-with-the-flow repos as deprecated? To save time for the next person. Thanks!
Closing this PR

**Comment by bjartek** [comment]
I have archived go-with-the-flow and replaced the readme with a redirect. Thank you.

**Pull request closed without merging**
